# Generated by Django 5.1 on 2024-09-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='coast_price',
            new_name='cost_price',
        ),
    ]
